spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EasyBank cards related QA APIs "
  contactDetails:
    name: "Vadim Nosov - QA Lead"
    email: "vadim.nosov@easybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267