spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EasyBank cards related prod APIs "
  contactDetails:
    name: "Andrey Kolosov - Product Owner"
    email: "andrey.kolosov@easybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721