spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EasyBank cards related prod APIs "
  contactDetails:
    name: "Anna Krasnova - Product Owner"
    email: "anna.krasnova@easybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721