services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "belyaev84/configserver:0.8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "belyaev84/eurekaserver:0.8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "belyaev84/accounts:0.8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5432/accountsdb"
    depends_on:
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "belyaev84/loans:0.8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansdb:5432/loansdb"
    depends_on:
      eurekaserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "belyaev84/cards:0.8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsdb:5432/cardsdb"
    depends_on:
      eurekaserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  easybank:
    driver: "bridge"
